/**
 * ShopContext.jsx
 *
 * Global state management for the E-Shop application using React Context API.
 *
 * This context provides:
 *  - `products`      — full product list (seeded from data/products.js, persisted to localStorage)
 *  - `cartItems`     — map of { productId: quantity }, persisted to localStorage
 *  - `user`          — logged-in user object (or null), persisted to localStorage
 *
 * All mutations (add/remove cart items, add/remove products, login/logout) are
 * exposed through the context value so any component can access them without
 * prop drilling.
 *
 * NOTE: localStorage persistence means cart and session survive page refreshes,
 * but this is purely client-side — there is no backend integration yet.
 */

import React, { createContext, useState, useEffect } from 'react';
import { products as initialProducts } from '../data/products';

// Create the context with a null default — consumers should always be wrapped
// inside ShopContextProvider, so the null default should never actually be used.
export const ShopContext = createContext(null);

/**
 * ShopContextProvider
 *
 * Wraps the component tree and makes all shop state available via context.
 * Uses lazy initializer functions in useState(() => ...) so localStorage is
 * only read once on mount, not on every render.
 *
 * @param {React.ReactNode} props.children - Child components to provide context to
 */
export const ShopContextProvider = (props) => {
    /**
     * products state
     * Initialized from localStorage if a saved list exists (e.g. the admin has
     * added/removed products), otherwise falls back to the static seed data.
     */
    const [products, setProducts] = useState(() => {
        const savedProducts = localStorage.getItem('products');
        return savedProducts ? JSON.parse(savedProducts) : initialProducts;
    });

    /**
     * cartItems state
     * Stored as a plain object: { [productId]: quantity }
     * Using an object (map) rather than an array makes O(1) lookups by product ID easy.
     */
    const [cartItems, setCartItems] = useState(() => {
        const saved = localStorage.getItem('cartItems');
        return saved ? JSON.parse(saved) : {};
    });

    /**
     * user state
     * When a user logs in, we store { email, name } here.
     * When they log out, this becomes null and the key is removed from localStorage.
     */
    const [user, setUser] = useState(() => {
        const savedUser = localStorage.getItem('user');
        return savedUser ? JSON.parse(savedUser) : null;
    });

    // ─── Persistence Effects ─────────────────────────────────────────────────

    // Keep the products list in sync with localStorage whenever it changes.
    // This ensures admin additions/removals persist across page reloads.
    useEffect(() => {
        localStorage.setItem('products', JSON.stringify(products));
    }, [products]);

    // Sync cart to localStorage on every cart change so the user's basket
    // survives navigation and browser refreshes.
    useEffect(() => {
        localStorage.setItem('cartItems', JSON.stringify(cartItems));
    }, [cartItems]);

    // Sync user session to localStorage. We remove the key entirely on logout
    // rather than storing a null string, which keeps localStorage clean.
    useEffect(() => {
        if (user) {
            localStorage.setItem('user', JSON.stringify(user));
        } else {
            localStorage.removeItem('user');
        }
    }, [user]);

    // ─── Auth Handlers ────────────────────────────────────────────────────────

    /**
     * login
     * Stores the user object in state (and, via the effect above, in localStorage).
     *
     * @param {Object} userData - Should contain at least `email` and `name`
     */
    const login = (userData) => {
        setUser(userData);
    };

    /**
     * logout
     * Clears the user from state. The useEffect above will remove it from localStorage.
     */
    const logout = () => {
        setUser(null);
    };

    // ─── Product Handlers ─────────────────────────────────────────────────────

    /**
     * addProduct
     * Appends a new product object to the end of the products list.
     * The ID is expected to be generated by the caller (AdminDashboard uses Date.now()).
     *
     * @param {Object} product - Full product object including id, name, category, price, image
     */
    const addProduct = (product) => {
        setProducts((prev) => [...prev, product]);
    };

    /**
     * removeProduct
     * Filters out the product with the given ID from the list.
     * Does not clean up cartItems — if the product was in the cart it will just
     * appear with no matching product info (getTotalCartAmount guards against this).
     *
     * @param {string} id - Product ID to remove
     */
    const removeProduct = (id) => {
        setProducts((prev) => prev.filter((product) => product.id !== id));
    };

    // ─── Cart Handlers ────────────────────────────────────────────────────────

    /**
     * addToCart
     * Increments the quantity for itemId by 1, creating the key if it doesn't exist yet.
     * Using functional update pattern to avoid stale-closure issues.
     *
     * @param {string} itemId - Product ID to add
     */
    const addToCart = (itemId) => {
        setCartItems((prev) => ({ ...prev, [itemId]: (prev[itemId] || 0) + 1 }));
    };

    /**
     * removeFromCart
     * Decrements the quantity for itemId by 1. If the quantity reaches 0,
     * the key is deleted from the cart object to keep things clean.
     *
     * @param {string} itemId - Product ID to decrement
     */
    const removeFromCart = (itemId) => {
        setCartItems((prev) => {
            const newCart = { ...prev };
            if (newCart[itemId] > 0) {
                newCart[itemId] -= 1;
                // Remove the key entirely when quantity hits zero
                if (newCart[itemId] === 0) delete newCart[itemId];
            }
            return newCart;
        });
    };

    /**
     * updateCartItemCount
     * Sets the quantity for a cart item to an exact value.
     * Used by the manual quantity input field in the Cart page.
     * Passing 0 removes the item from the cart map entirely.
     *
     * @param {number} newAmount - The desired quantity (0 to remove)
     * @param {string} itemId    - Product ID to update
     */
    const updateCartItemCount = (newAmount, itemId) => {
        setCartItems((prev) => {
            const newCart = { ...prev };
            if (newAmount === 0) {
                // Remove the entry rather than leaving { id: 0 } in state
                delete newCart[itemId];
            } else {
                newCart[itemId] = newAmount;
            }
            return newCart;
        });
    };

    /**
     * clearCart
     * Resets cartItems to an empty object — called after a successful checkout.
     */
    const clearCart = () => {
        setCartItems({});
    };

    // ─── Derived Data ─────────────────────────────────────────────────────────

    /**
     * getTotalCartAmount
     * Calculates the total price of all items currently in the cart.
     * Looks up each product by ID to get its price. Guards against orphaned
     * cart entries (products that were removed from the catalogue while they
     * were still in the cart).
     *
     * @returns {number} Total price in dollars
     */
    const getTotalCartAmount = () => {
        let totalAmount = 0;
        for (const item in cartItems) {
            if (cartItems[item] > 0) {
                // Find product info for this item
                let itemInfo = products.find((product) => product.id === item);
                if (itemInfo) {
                    totalAmount += cartItems[item] * itemInfo.price;
                }
            }
        }
        return totalAmount;
    };

    /**
     * getTotalCartItems
     * Returns the total number of individual items (not unique products) in the cart.
     * This is used to drive the badge counter on the nav cart icon.
     *
     * @returns {number} Sum of all item quantities
     */
    const getTotalCartItems = () => {
        let totalItems = 0;
        for (const item in cartItems) {
            totalItems += cartItems[item];
        }
        return totalItems;
    };

    // Bundle everything the rest of the app needs into a single context value.
    // NOTE: getTotalCartAmount appears twice in the original object — likely a copy-paste
    // oversight. Keeping it as-is to avoid unintended side effects.
    const contextValue = {
        cartItems,
        addToCart,
        removeFromCart,
        updateCartItemCount,
        clearCart,
        getTotalCartAmount,
        getTotalCartAmount, // duplicate key — last one wins in JS, harmless but worth noting
        getTotalCartItems,
        user,
        login,
        logout,
        products,
        addProduct,
        removeProduct
    };

    return (
        <ShopContext.Provider value={contextValue}>
            {props.children}
        </ShopContext.Provider>
    );
};
